### ISSUE TITLE
nuget?

### ISSUE THREAD

**Issue by kinetiq** [neon-sunset/Pinecone.NET#1]
Hey, would you mind publishing a nuget package? I would love to play with this.

**Comment by neon-sunset** [comment]
Hi Brian, I'm still working on this. gRPC part is mostly done but REST and metadata filters' UX needs work. Check back by the end of this week :)

**Comment by kinetiq** [comment]
Alright, good luck! I'll use it as soon as it's ready.  Maybe up the dosage to 600mg. :)

**Comment by neon-sunset** [comment]
The package has been released: https://www.nuget.org/packages/Pinecone.NET
It requires either .NET 7 or .NET 8 preview and should support all features exposed by the official Pinecone libraries. Give it a try and let me know whether it works for you as intended.

**Comment by kinetiq** [comment]
You did it! I've got a hackathon starting in 6m, we might be able to use this. Thanks a lot!
