### ISSUE TITLE
Automatic Conversion to MetadataValue for Various Object Types

### ISSUE THREAD

**Issue by PabloSergi** [neon-sunset/Pinecone.NET#17]
Hello, first of all  I'm not a strong c# developer, and i need an advice.  Currently I'm trying to use the Upsert method from your library to upload vectors, for which I need to populate the Vector properties, including MetadataMap. However, I'm encountering an issue when trying to convert various types of objects to MetadataValue.

Here is a brief overview of my current process:

1) I utilize the Upsert method as follows:

```
public Task<uint> Upsert(IEnumerable<Vector> vectors, string? indexNamespace = null)
{
    return Transport.Upsert(vectors, indexNamespace);
}
```

2) I populate Vector properties:

```
return new Pinecone.Vector
{
    Id = vector.Item1,
    Values = vector.Item2.Select(d => (float)d).ToArray(),
    Metadata = metadataMap
};
```

3) To fill the MetadataMap, I need to utilize MetadataValue:

```
public sealed class MetadataMap : Dictionary<string, MetadataValue>
{
}
```

4) However, to fill the MetadataValue, I need to use the following internal method:

```
[JsonConverter (typeof(MetadataValueConverter))]
public readonly struct MetadataValue : IEquatable<MetadataValue>
{
	public object? Inner { get; }

	[MethodImpl (MethodImplOptions.AggressiveInlining)]
	internal MetadataValue (object? value)
	{
		Inner = value;
	}
}
```

At this stage, I'm required to implement a potentially complex method to determine the type of each metadata value and convert it appropriately. I'm facing a scenario where the types of objects can vary, and it's not straightforward to prepare the metadata objects for the Upsert method.

Is there a simpler way provided by your library to automatically convert different objects to MetadataValue, or is there a recommended approach to handling this situation? I'm looking for a more straightforward solution to handle these data transformations before calling the Upsert method.

Your guidance would be greatly appreciated. Thank you in advance.

**Comment by neon-sunset** [comment]
Hi Pablo. Yes, `MetadataValue` was made specifically to not have to deal with this manually. It is implicitly convertible to from `bool`, `string`, various numeric types (just cast to `double` if doesn't work), `MetadataMap` itself to nest complex metadata props, and `MetadataValue[]`/`List<MetadataValue>`.

For example, if you want to have  a method that returns a pinecone vector, you could write it as following:
```cs
...
return new()
{
    Id = vector.Item1,
    Values = vector.Item2.Select(d => (float)d).ToArray(), // By the way, is `d` here not float?
    Metadata = new()
    {
        ["value1"] = someStringValue,
        ["value2"] = someNumericValue,
        ["value3"] = default // this is if you want to set it to Null,
        ["value4"] = new MetadataValue[] { "abc, "cde" },
        ["value5"] = new MetadataMap
        {
            ["nestedValue1"] = nested1,
            ["nestedValue2"] = nested2
        } 
    }
};
```

All types that `MetadataValue` supports can be *implicitly casted* to it. This means the following expression is legal:
```cs
MetadataValue value = 3.14f;
```
and we take advantage of that when declaring metadata dictionary.

**Comment by neon-sunset** [comment]
@PabloSergi since the issue has been inactive for some time, I'm going to close it. Should you need any assistance - feel free to reopen it back. Thank for you for giving `Pinecone.NET` a try!
