### ISSUE TITLE
Pinecone withing Semantic Kernel blows up

### ISSUE THREAD

**Issue by securigy** [neon-sunset/Pinecone.NET#18]
I found your repository and liked its clarity and so I implemented it in my exploratory project... only to find Semantic Kernel a few days later... I cloned SK repo and am trying different examples, especially the Example38 that has Pinecone integration in it.
Below I pasted the entire code. Obviously, I replaced the keys with those I obtained from Pinecone and from OpenAI. However, I get the exception at the indicated line.
The exception message: 
`Index creation is not supported within memory store. It should be created manually or using CreateIndexAsync. Ensure index state is Ready.`

From that I understand that I need to do indexing on my own, which would be very strange... If this is the case, how would I do it. Do you think I should use your library (also looks unintuitive solution) in order to create index? I saw you comments on Semantic Kernel, so I know you are aware of it, and may be know something I do not...

Are you able to run the below example without errors?

Leon

`using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.Connectors.Memory.Pinecone;
using Microsoft.SemanticKernel.Connectors.Memory.Pinecone.Model;
using Microsoft.SemanticKernel.Memory;
using RepoUtils;

// ReSharper disable once InconsistentNaming
/// <summary>
///  This example shows how to use the PineconeMemoryStore to store and retrieve memories with Pinecone assuming
///  you have a Pinecone account and have created an index. You can create an index using the Pinecone UI or
///  instead initialize the index using <see cref="IPineconeClient.CreateIndexAsync(IndexDefinition, System.Threading.CancellationToken)"/>.
///  But note that it can take a few minutes for the index to be ready for use.
/// </summary>
public static class Example38_Pinecone
{
    private const string MemoryCollectionName = "pinecone-test";

    public static async Task RunAsync()
    {
        string apiKey = Env.Var("PINECONE_API_KEY");
        string pineconeEnvironment = Env.Var("PINECONE_ENVIRONMENT");

        PineconeMemoryStore memoryStore = new(pineconeEnvironment, apiKey);

        IKernel kernel = Kernel.Builder
            .WithLogger(ConsoleLogger.Log)
            .WithOpenAITextCompletionService("text-davinci-003", Env.Var("OPENAI_API_KEY"))
            .WithOpenAITextEmbeddingGenerationService("text-embedding-ada-002", Env.Var("OPENAI_API_KEY"))
            .WithMemoryStorage(memoryStore)
            .Build();

        Console.WriteLine("== Printing Collections in DB ==");

        IAsyncEnumerable<string> collections = memoryStore.GetCollectionsAsync();

        await foreach (string collection in collections)
        {
            Console.WriteLine(collection);
        }

        Console.WriteLine("== Adding Memories ==");

        Dictionary<string, object> metadata = new()
        {
            { "type", "text" },
            { "tags", new List<string>() { "memory", "cats" } }
        };

        string additionalMetadata = System.Text.Json.JsonSerializer.Serialize(metadata);
        
        // !!! EXCEPTION AT THIS LINE
        string key1 = await kernel.Memory.SaveInformationAsync(MemoryCollectionName, "british short hair", "cat1", null, additionalMetadata);
        string key2 = await kernel.Memory.SaveInformationAsync(MemoryCollectionName, "orange tabby", "cat2", null, additionalMetadata);
        string key3 = await kernel.Memory.SaveInformationAsync(MemoryCollectionName, "norwegian forest cat", "cat3", null, additionalMetadata);

        Console.WriteLine("== Retrieving Memories Through the Kernel ==");
        MemoryQueryResult? lookup = await kernel.Memory.GetAsync(MemoryCollectionName, "cat1");
        Console.WriteLine(lookup != null ? lookup.Metadata.Text : "ERROR: memory not found");

        Console.WriteLine("== Retrieving Memories Directly From the Store ==");
        var memory1 = await memoryStore.GetAsync(MemoryCollectionName, key1);
        var memory2 = await memoryStore.GetAsync(MemoryCollectionName, key2);
        var memory3 = await memoryStore.GetAsync(MemoryCollectionName, key3);

        Console.WriteLine(memory1 != null ? memory1.Metadata.Text : "ERROR: memory not found");
        Console.WriteLine(memory2 != null ? memory2.Metadata.Text : "ERROR: memory not found");
        Console.WriteLine(memory3 != null ? memory3.Metadata.Text : "ERROR: memory not found");

        Console.WriteLine("== Similarity Searching Memories: My favorite color is orange ==");
        IAsyncEnumerable<MemoryQueryResult> searchResults = kernel.Memory.SearchAsync(MemoryCollectionName, "My favorite color is orange", 1, 0.8);

        await foreach (MemoryQueryResult item in searchResults)
        {
            Console.WriteLine(item.Metadata.Text + " : " + item.Relevance);
        }
    }
}
`

**Comment by neon-sunset** [comment]
Hi Leon. Pinecone connector implementation in Semantic Kernel is...not great. It also uses naming that differs from actual operation names in Pinecone API so I can understand the confusion.

Semantic Kernel in general is more bloated than it could have been but it's not surprising given it was written by developers who most likely worked with enterprise code only for more than a decade.

Anyway, for what you are trying to achieve you do not need my library, because SK's has its own `PineconeClient` implementation which you can use as following:
```cs
using Microsoft.SemanticKernel.Connectors.Memory.Pinecone;
using Microsoft.SemanticKernel.Connectors.Memory.Pinecone.Model;

using var pinecone = new PineconeClient(environment, apiKey);

await pinecone.CreateIndexAsync(new("pinecone-test")
{
    Dimension = 1536,
    PodType = PodType.S1X1,
    Metric = IndexMetric.Euclidean
});
```

I'm planning to contribute a connector rewrite to SK, hopefully sorting out some of its rough edges around dev experience and removing arbitrary choices like not allowing index creation via its memory store abstraction (my guess why it is like that - it takes time for Pinecone to provision a new index and there is no way to know how long it will take without periodically polling for index details).

Keep in mind that SK uses a different terminology than Pinecone which causes confusion so just in case:
- SK collection is Pinecone index
- Pinecone collection is an immutable Pinecone index snapshot

**Comment by securigy** [comment]
Thanks for your detailed reply. Somewhere thereafter I read that SK is not creating the index... but how you do it nowhere can be found. So, I will try your suggestion right away. I presume that their SK development is not mature yet - they are using special Embeddings API Key for Azure and based on my Azure search this thing does not exist - that's why they create all Embeddings examples using passthrough to OpenAI using OpenAI Key... 

Are there additional open-source vector DBs that have decent C# bindings? To my regret it seems that AI marching to the tune of Python. I don't hate it, but don't like it either - reminds me those stampedes toward Visual Basic at the time...

**Comment by securigy** [comment]
I implemented your suggestion, but unfortunately got the same exception on the same line...


                'PineconeMemoryStore memoryStore = new(pineconeEnvironment, apiKey);
                  using var pinecone = new PineconeClient(pineconeEnvironment, apiKey);
                  await pinecone.CreateIndexAsync(new("pinecone-test")
                {
                    Dimension = 1536,
                    PodType = PodType.S1X1,
                    Metric = IndexMetric.Euclidean
                });

                IKernel kernel = Kernel.Builder
                    .WithOpenAITextCompletionService("text-davinci-003", openAiKey)
                    .WithOpenAITextEmbeddingGenerationService("text-embedding-ada-002", openAiKey)
                    .WithMemoryStorage(memoryStore)
                    .Build();`

Same Exception on the same line:
                    string key1 = await kernel.Memory.SaveInformationAsync(MemoryCollectionName, "british short hair", "cat1", null, additionalMetadata);

**Comment by neon-sunset** [comment]
> Are there additional open-source vector DBs that have decent C# bindings? To my regret it seems that AI marching to the tune of Python. I don't hate it, but don't like it either - reminds me those stampedes toward Visual Basic at the time...

By C# bindings...do you mean SK connectors? If yes, then unfortunately I can't give any suggestions, haven't used SK myself in any project because implementing an agent pattern was easy enough without it for now. And compared to Langchain, I really dislike the naming and abstraction choices SK took hence not trying it out just yet in a serious way.

**Comment by neon-sunset** [comment]
> I implemented your suggestion, but unfortunately got the same exception on the same line...

Are you sure? You need to wait for the index to get provisioned (you can check index status if you log into pinecone dashboard or using the `DescribeIndexAsync`, it has a property that describes actual index status/state).

**Comment by securigy** [comment]
So, I added the line to the code after index creation (although await is supposed to comeback when index is done).
However, this time the CreatePineconeIndex does not return at all...

`                
                PineconeMemoryStore memoryStore = new(pineconeEnvironment, apiKey);`
`                using var pinecone = new PineconeClient(pineconeEnvironment, apiKey);
`
               
                Log.Verbose("Calling CreatePineconeIndex...");`

                await pinecone.CreateIndexAsync(new("pinecone-test")
                {
                    Dimension = 1536,
                    PodType = PodType.S1X1,
                    Metric = IndexMetric.Euclidean
                });

                Task t = pinecone.DescribeIndexAsync("pinecone-test");`

Here is what my console shows:
15:14:33.377 Verbose Main Thread MainForm+RunAsync       Calling CreatePineconeIndex...
'GptModelTrainer.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.5\System.Runtime.Serialization.Primitives.dll'. 
'GptModelTrainer.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.5\System.Net.Quic.dll'. 
'GptModelTrainer.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.5\System.Net.Sockets.dll'. 
'GptModelTrainer.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.5\System.Net.NameResolution.dll'. 
15:14:33.462 Verbose Main Thread MainForm+RunAsync    RunAsync exiting
Exception thrown: 'System.Net.Http.HttpRequestException' in System.Net.Http.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in Microsoft.SemanticKernel.Connectors.Memory.Pinecone.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in System.Private.CoreLib.dll
15:14:35.761 Verbose Main Thread MainForm+PinecodeRibbonBtn_ItemClick PinecodeRibbonBtn_ItemClick exiting
The thread 0x118b8 has exited with code 0 (0x0).
The thread 0x14830 has exited with code 0 (0x0).
The thread 0x1774 has exited with code 0 (0x0).

**Comment by neon-sunset** [comment]
You can't call `CreateIndexAsync` multiple times because it will fail if the index already exists. After all, you are mutating the state of your vector DB.

I think the best course of action here is to debug the code over using console which doesn't have all details, and reading documentation because there is some required knowledge to use SK + Vector DBs:
- https://docs.pinecone.io/docs/indexes
- https://docs.pinecone.io/docs/manage-indexes
- https://github.com/microsoft/semantic-kernel/blob/main/samples/notebooks/dotnet/06-memory-and-embeddings.ipynb

You could try using volatile memory store first and once that part works, move over to persistence with Pinecone connector or other options.
