### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by securigy** [neon-sunset/Pinecone.NET#19]
After my unsuccessful attempt with Semantic Kernel, I switched to plain OpenAI API Embedding APIs and your Pinecone .NET library, along with reading original Pinecone documentation as you recommended. So I am hoping here to pick your wisdom and experience with some general Pinecone questions:

So, the embeddings OpenAI API produce 1536-dimensional vectors and I don't think it is configurable. At the same time the free pinecone account is limited to 768-dimensional vectors at p1 and s1 pods that come with the free account:
[https://www.pinecone.io/learn/testing-p2-collections-scaling/#vertical-scaling-on-p1-and-s1](url)
and somehow many people use it so there must be a solution for that... What is it?
I see that I can create index of 1536-d so does it mean I will be automatically switched to non-free account and if I leave index running for a month will be charged about $70?
https://www.pinecone.io/pricing/

**Comment by neon-sunset** [comment]
This can't be right, I just double-checked and my (free) P1 index with 1536 got provisioned. Docs say 1M 768-wide vectors per P1 pod which is just an estimation, not actual pod limit.

**Comment by securigy** [comment]
OK, thanks.
