### ISSUE TITLE
After creating index ListIndexes never returns

### ISSUE THREAD

**Issue by securigy** [neon-sunset/Pinecone.NET#21]
I deleted all indexes first. Then restarted the app. Then created new index "index1", then shutdown the app.
Then restarted the app and upon start I call ListIndexes (after I instantiate the library object) and this call never returns.
I either don't understand how to use the library or Pinecone itself is really not ready... Any ideas, have you seen anything like that?
         `        
        private void MainForm_Load(object sender, EventArgs e)
        {
            using (Log.VerboseCall())
            {
                mEmbeddings = new EmbeddingsAPI.Embeddings();
                mEmbeddings.EmbeddingsDoneEvent += Embeddings_EmbeddingsDoneEvent;

                if (mPineconeDb == null)
                {
                    mPineconeDb = new PineconeDb();
                    mPineconeDb.CreateInstance(pineconeApiKey, pineconeEnv);
                    mPineconeDb.SetTransportType(PineconeTransport.REST);

                    bool ret = mPineconeDb.IsIndexReady().Result;
                    if (ret == true)
                    {
                        SegmentDoRibbonBtn.Enabled = true;
                        ClearRibbonBtn.Enabled = true;
                    }
                    else
                    {
                        SegmentDoRibbonBtn.Enabled = false;
                        ClearRibbonBtn.Enabled = false;
                    }
                }
            }
        }

        public void CreateInstance(string apiKey, string env = null) 
        {
            using (Log.VerboseCall())
            {

                mApiKey = apiKey;
                mEnv = env;

                mPinecone = new PineconeClient(apiKey, env);
            }
        }

        public async Task<bool> IsIndexReady()
        {
            using(Log.VerboseCall())
            {
                IndexName[] indexes = await mPinecone.ListIndexes();

                Index<RestTransport> idx = await mPinecone.GetIndex<RestTransport>(indexes[0]);
                if (idx.Status.IsReady)
                {
                    Log.Verbose("Index is ready");
                    return true;
                }
                else
                {
                    Log.VerboseFormat("Index state: {0}", idx.Status.ToString());
                    return false;
                }
            }
        }

`

**Comment by securigy** [comment]
I create index then call GetIndex on it and the Status then is IsReady=false, so I cannot use it right away, and there is no event that I can handle that will notify when index is ready. Therefore, I need to call GetIndex in a loop at some interval until I discover that IsReady=true. However, the 1st call in this loop goes in and never returns... and I see in Output screen:

Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll

**Comment by neon-sunset** [comment]
You need to step through with the debugger and see what is the actual exception message, or print it out in some other way, and then take it from there.
