### ISSUE TITLE
Empty Metadata

### ISSUE THREAD

**Issue by securigy** [neon-sunset/Pinecone.NET#28]
I successfully ingested 15 vectors with metadata based on specific document, then created embedding for my prompt. Then I successfully queried the pinecone, only to discover that it returns empty metadata… Any ideas why?

               `
                List<EmbeddingsData> embeddingsList = mEmbeddings.CreateEmbeddings(QRichEditCtrl.Text, "en-US");

                if (embeddingsList != null && embeddingsList.Count > 0)
                {
                    float[] floatArray = Array.ConvertAll(embeddingsList[0].Embedding.ToArray(), value => (float)value);

                    // Query scored vectors by a new, previously unseen vector
                    ScoredVector[] scoredVectors = await mIndex.Query(floatArray, topK: 10);
                    List<ScoredVector> scoredList = scoredVectors.ToList();
                   // Get the vector with max score
                    ScoredVector maxScoredVector = scoredList.Aggregate((i1, i2) => i1.Score > i2.Score ? i1 : i2);
                    string ID = maxScoredVector.Id;

                    // metadata is empty... 
                }`

**Comment by neon-sunset** [comment]
Have you looked at `.Query` method signature?

**Comment by neon-sunset** [comment]
Duplicates https://github.com/neon-sunset/Pinecone.NET/issues/15

**Comment by securigy** [comment]
Are you saying that I had to define filter to get back Metadata? Isn't filter for limiting the output?

**Comment by neon-sunset** [comment]
You must specify `includeMetadata: true`. This follows official behavior:  https://github.com/neon-sunset/Pinecone.NET/blob/main/src/Index.cs#L57
The only difference is `includeValues` is by default `true` so to skip those, you must specify `false`.

**Comment by securigy** [comment]
Thanks. I was looking at your examples... but should have explored the API's better. It works now.
