### ISSUE TITLE
Vectors returned in Fetch have different Dimensions

### ISSUE THREAD

**Issue by ra-one** [neon-sunset/Pinecone.NET#40]
I have Pinecone index with Dimensions 1536, but when i use Fetch it returns the vectors with Dimensions 2048. I did fetch using postman and python and they return vectors with correct Dimensions of 1536.

Also I can not find update which takes vector ID instead of vector it-self (just trying to update metadata only), this was the problem i was trying to solve by fetching vectors and then update the metadata.

**Comment by neon-sunset** [comment]
@ra-one thank you for submitting the issue, indeed, I can reproduce it with `GrpcTransport`.

I will fix it and push updated nuget shortly. In the meantime, you can switch to `RestTransport` which will have the array of length `1536` in its query and fetch responses.

By the way, you *can* query vectors both by a new, previously unseen vector or by pre-existing vector ID you set during upsert. You can also fetch vectors by ID if you don't want to query them.

**Comment by neon-sunset** [comment]
Fixed in https://github.com/neon-sunset/Pinecone.NET/releases/tag/1.2.2

**Comment by ra-one** [comment]
@neon-sunset thank you for the prompt reply, i appreciate it.

My use case is: I want to only update `metadata` for the number of vectors, and as far as i can see the library's `update` method requires vector as param `  public Task Update(Vector vector, string? indexNamespace = null) ... ` so the only way i can provide vector is first have to `fetch` the vector edit/update the `metadata` and then call `update`.

It seem we dont have `update` like described in/at [docs.pinecone.io/reference/update](https://docs.pinecone.io/reference/update) where we can only provide `vector ID` and `setMetadata` object which should only overwrite the `metedata` for that `vector`
Also I will be happy to contribute/help if we were to write/add new `update` method that takes in `id` and `setMetadata` object.

Please do let me know if my thinking is not correct/ or i missed something.

**Comment by neon-sunset** [comment]
> My use case is: I want to only update metadata for the number of vectors, and as far as i can see the library's update method requires vector as param  public Task Update(Vector vector, string? indexNamespace = null) ... so the only way i can provide vector is first have to fetch the vector edit/update the metadata and then call update.

Yes, `values` being mandatory notwithstanding, there is no way around it but to fetch vectors first and update them one by one (you can dispatch multiple calls concurrently).
