### ISSUE TITLE
Porting to .NET Framework

### ISSUE THREAD

**Issue by securigy** [neon-sunset/Pinecone.NET#46]
I use the library in one of my experimental projects and now need to use it in desktop version of one of the Office products (as add-in). Unfortunately, desktop Office add-in only compatible with .NET Framework.
How difficult would it be porting the library to .NET 4.8? What issues do you see with that?

**Comment by neon-sunset** [comment]
This library is specifically made to be targeted for .NET 7 and upcoming .NET 8.0 LTS. Supporting NS2.0 is specifically a non goal. However, you could attempt to fork it and port it manually - there isn't a lot of code to start with and most complexity was just figuring out the tooling.

**Comment by securigy** [comment]
Thanks. I will try to delegate it to one of my resources.
