### ISSUE TITLE
Support for .NET6

### ISSUE THREAD

**Issue by neon-sunset** [neon-sunset/Pinecone.NET#48]
### Discussed in https://github.com/neon-sunset/Pinecone.NET/discussions/47

<div type='discussions-op-text'>

<sup>Originally posted by **tegra** August 15, 2023</sup>
Hi,

Due to environmental constraints, we are forced to use .NET6. Is there a plan to support .NET6?</div>

**Comment by neon-sunset** [comment]
Added in https://github.com/neon-sunset/Pinecone.NET/releases/tag/1.3.0

**Comment by tegra** [comment]
Thank you!!
