### ISSUE TITLE
Question about vector metadata

### ISSUE THREAD

**Issue by securigy** [neon-sunset/Pinecone.NET#62]
According to Pinecone the vector metadata can have items with value of the type List<string>.
However, when I use the library in the following way, it won't build:

`
                        vec.Metadata.Add("TimeIngested", segList[i].TimeIngested);
                        vec.Metadata.Add("TimeSrcModified", segList[i].TimeSrcModified);
                        vec.Metadata.Add("NamedEntityList", segList[i].NamedEntityList);
`
where in the 3rd line I have: segList[i].NamedEntityList is List<string>, it will not build saying it cannot convert it to MetadataValue...

So how to I handle this:
I cannot do the following because it is Dictionary and it will overwrite itself:
`                        vec.Metadata.Add("NamedEntityList", segList[i].NamedEntityList[0]);
                        vec.Metadata.Add("NamedEntityList", segList[i].NamedEntityList[1]);`

So what do I do?

**Comment by neon-sunset** [comment]
The list simply needs to be compatible. Also use collection initializer to avoid code bloat.

See https://github.com/neon-sunset/Pinecone.NET/discussions/11#discussioncomment-7073331

**Comment by securigy** [comment]
I am not sure I really understand what you mean:
"The list simply needs to be compatible." - the Pinecone docs say it supports List<string>. I simply do not understand how to convert it to be Metadata...
"Also use collection initializer to avoid code bloat." - what does it have to do with collections?

**Comment by neon-sunset** [comment]
Have you tried populating the list first and then adding it to metadata?

**Comment by securigy** [comment]
Yes, I checked the link and still do not understand how I populate metadata with the list of keywords. All I could come up with is this:
`                        string csv = "";
                        for (int j = 0; j < segList[i].NamedEntityList.Count; j++)
                            csv += segList[i].NamedEntityList[j] + ",";

                        vec.Metadata.Add("NamedEntityList", csv);
`
But then, I am not sure how to construct the filter because [$in] is supposed to check 'among' the items, not the CSV string...

So my question is still: how to populate metadata with keyword list or array?

**Comment by securigy** [comment]
So, after some thought I came up with the following, does it seem like a correct way to include a list of keywords in metadata?

`                       
                        MetadataValue[] mvArr = new MetadataValue[segList[i].NamedEntityList.Count];
                        for (int j = 0; j < mvArr.Length; j++)
                        {
                            mvArr[j] = segList[i].NamedEntityList[j];
                        }
                        vec.Metadata.Add("NamedEntityList", mvArr);

`

**Comment by neon-sunset** [comment]
The initial question and follow information is unclear, but from what I can see you have issues with mapping to metadata representation to upsert and then filter vectors.

The basics of this is `MetadataMap` is a dictionary keyed by `string` with `MetadataValue` values. Each `MetadataValue` can be converted from either primitives like `int`, `float`, `bool`, `string` or represent a nested collection of `MetadataValue`s namely `MetadataValue[]`, `List<MetadataValue>` and `MetadaMap`.

To work with C# representation of Pinecone metadata values successfully (which closely follows MongoDB conventions), I suggest reading through the discussion at the link referenced in my previous message (https://github.com/neon-sunset/Pinecone.NET/discussions/11#discussioncomment-7073331) and also reviewing examples in a response to a pinned question here which contains more examples on how to build `MetadataMap`s: https://github.com/neon-sunset/Pinecone.NET/discussions/31#discussioncomment-6302396
