### ISSUE TITLE
How do I create a Vector object?

### ISSUE THREAD

**Issue by clement-fifty** [neon-sunset/Pinecone.NET#63]
Hey

I must be missing something obvious here.

I want to create a Vector to then use Upsert.

Whatever I do, I get the error:

> Constructors of types with required members are not supported in this version of your compiler.

```
// both those example give this error
var vector = new Vector
{
    Id = dbVector.Id,
    Values = dbVector.Values
};

new Vector
{
    Id = "vector1",
    Values = new float[] { 0.1f, 0.2f, 0.3f },
    Metadata = new MetadataMap
    {
        ["genre"] = "horror",
        ["duration"] = 120
    }
}
```

I don't see any other constructor for Vector and the default constructor shows an error.

My project is in net6.0, C# 10.0 and the package is version 1.3.0. 

Note: this is not a build error, but shows as error in the IDE.

What's the proper way to initiate a Vector then?

**Comment by neon-sunset** [comment]
Hi @clement-fifty 

You may need to set <LangVersion> of your project to 11 (or Latest, provided you have .NET 7 SDK installed, which you need in either case).

Let me know if this works.
