### ISSUE TITLE
metadata filter

### ISSUE THREAD

**Issue by danpak6** [neon-sunset/Pinecone.NET#8]
How can I query by metadata filter? 
https://docs.pinecone.io/docs/metadata-filtering

Thank you!

**Comment by neon-sunset** [comment]
@danpak6 the version that supports querying with metadata filtering has been published: https://www.nuget.org/packages/Pinecone.NET/1.2.0
Example:
```cs
using var index = await pinecone.GetIndex("my-test-index);

var filter = new MetadataMap
{
   ["genre"] = "horror",
   ["year"] = 1963
};

var scored = await index.Query("birds", topK: 5, filter);
```
or
```cs
var scored = await index.Query("birds", topK: 5, new()
{
   ["genre"] = "horror",
   ["year"] = 1963
});
```
Standard limitations / rules for working with Pinecone's metadata type apply. 
Let me know how it works for you.

**Comment by neon-sunset** [comment]
I don't think that's true. `.Query` method requests an array of `ScoredVector`s. If neither vector id nor previously unsees vector values provided, there is nothing to score vectors in the index against, such an action just would not make sense.

Metadata delcaration format in C# is subject to strong type system which makes it somewhat clunkier to work with when compared to JS or Python, therefore an expression `{"$and": [{"genre": "comedy"}, {"genre":"documentary"}]}` would map onto
```cs
var filter = new MetadataMap
{
   ["$and"] = new MetadataValue[]
   {
      new MetadataMap { ["genre"] = "comedy" },
      new MetadataMap { ["genre"] = "documentary" }
   }
}
```

MongoDB-style conditionals just happen to hit the worst case scenario when it comes to syntax. If you look at how the `MetadataMap` is implemented, it is a `Dictionary<string, MetadataValue>` where `MetadataValue` can be either a null, a string, a double, a MetadataValue[] or another MetadataMap which allows to express all states the metadata nodes can take.

**Comment by neon-sunset** [comment]
Thanks, I'm going to close the issue as done. Should you have any questions, feel free to open a new one or start a discussion (enabled now) 😄

**Comment by neon-sunset** [comment]
This would directly translate to C# code with this library:
```cs
using Pinecone;

using var pinecone = new PineconeClient("YOUR_API_KEY", "us-west1-gcp")
using var index = await pinecone.GetIndex("example-index");

var queryResponse = await index.Query(
   new[] { 0.1f, 0.2f, 0.3f, 0.4f },
   topK: 10,
   filter: new()
   {
      ["genre"] = new MetadataMap { ["$in"] = new MetadataValue[] { "comedy", "documentary", "drama" } }
   },
   includeMetadata: true);
```

the only "creative liberty" I took is `includeValues` being true by default, unlike in the official library.

**Comment by neon-sunset** [comment]
Pinecone allows two modes of querying:
- Query by a previously unseen vector (the overload that takes `float[] values` and optional `SparseValues? sparseValues`). The returned scored vectors present in your pinecone index will be scored against this vector;
- Query by an ID of a vector already present in your pinecone index (the overload that takes in `string id`)

The "birds" example assumes the index already has a vector with id "birds". This is just to showcase what methods the library has (and that they match the official API).

**Comment by neon-sunset** [comment]
I'm not sure, but this is probably best answered either by Pinecone documentation (see the examples section) or [community portal](https://community.pinecone.io/). I'm still learning vector DBs myself and wrote this library mostly because there was none in C#, which I love and wanted to use for this 🙂

**Comment by neon-sunset** [comment]
Have you checked https://docs.pinecone.io/docs/semantic-text-search ? It does seem like name-spacing would be the most safe/logical choice to achieve tenant separation. You could try tagging with metadata value "tenant": "tenantName" but I wouldn't be comfortable with such approach.

**Comment by neon-sunset** [comment]
The above code is expressible in C#, feel free to refer to one of the previous examples on how to work with metadata.
