### ISSUE TITLE
How to use with REST?

### ISSUE THREAD

**Issue by Melbourneandrew** [neon-sunset/Pinecone.NET#93]
I am unable to use gRPC in my current environment, I am wondering how I can make the client default to using the REST Transport methods instead of gRPC. Thanks!

**Comment by neon-sunset** [comment]
Hi Andrew,

You can select which type of transport to use for vector operations in the following way:
```cs
using Pinecone.Rest;

// Assuming you have a PineconeClient instance named 'pinecone'
using var index = await pinecone.GetIndex<RestTransport>(indexName);
```

Keep in mind that Pinecone had a lot of semi-breaking API changes lately, as evidenced by numerous reports on their forum for official clients, so let me know if something breaks.
